### ISSUE TITLE
Audio volume is not correct at startup

### ISSUE THREAD

**Issue by Vitty85** [XK9274/moonlight-app-miyoo#4]
When application starts streaming, the volume is high independently from Miyoo current volume setting, but after pressing any volume button it syncs (maybe a solution could be to fakely invoke a volume button pressing on startup as i suppose Drastic is doing so solve similar issue).

**Comment by XK9274** [comment]
Addressed in https://github.com/XK9274/moonlight-app-miyoo/commit/d3577807bed3f282ea987204c40087286260b680

**Comment by Vitty85** [comment]
I made an early test on commit and it seems ok now, the volume is coherent with level on Miyoo at application startup. I will wait for new release to test again and close issue.

**Comment by Vitty85** [comment]
The issue is fixed, tested in both 1.0 and 1.1
